version: 0.0
os: ubuntu
hooks:
  AfterInstall:
    - location: startserver.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
